export enum ErrorCode {
    SOURCE_CUSTOMER_NOT_FOUND = 'SOURCE_CUSTOMER_NOT_FOUND',
    TARGET_CUSTOMER_NOT_FOUND = 'TARGET_CUSTOMER_NOT_FOUND',
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
    PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
    REFUND_AMOUNT_EXCEEDS_PURCHASE_AMOUNT = 'REFUND_AMOUNT_EXCEEDS_PURCHASE_AMOUNT',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}